### ISSUE TITLE
Integrate travis with Beagle

### ISSUE THREAD

**Issue by allanbolipata** [mskcc/beagle#119]
Integrate travis to run the tests on Beagle repository on each PR.

**Comment by stevekm** [comment]
one thing we will need to figure out for this is how to run LIMS ETL tests. Currently, they require the IGO LIMS access and test import of an actual item set from IGO LIMS;

https://github.com/mskcc/beagle/blob/a2265e84103fa957a4ec6db4eaa1059c9bfdcf84/beagle_etl/tests/jobs/test_lims_etl_jobs.py#L31

This can also be time-consuming, since this test alone usually takes ~10-13s in my experience. Running this in Travis might be problematic, depending on how/where our Travis is set up. 

In more recent branches I have just started separating that LIMS test from the other tests which do not require external server access;

https://github.com/mskcc/beagle/blob/ad1c1aed01832f1f3ebff65ca8d98fb952145601/Makefile#L318-L330

Similar considerations might need to be made for other tests that require external server access.

One potential solution could be to mock the IGO LIMS external API response.
