### ISSUE TITLE
Roslin Operator output 'project_prefix' as a list, not a string

### ISSUE THREAD

**Issue by stevekm** [mskcc/beagle#164]
When you try to run the Roslin CWL `workflows/pair-workflow-sv.cwl` workflow with output from Beagle's Roslin Operator, the resulting JSON input file appears to be mis-configured. `cwltool` reports the error:

```
* the `project_prefix` field is
                                                                  not valid because
                                                                      the value is not string
```

The `project_prefix` output by Beagle looks like this:

```
"project_prefix": [
            "07264_G"
        ],
```

I think it should be like this instead?

```
"project_prefix": "07264_G",
```

Do we know why Beagle is outputting a list here?

**Comment by allanbolipata** [comment]
Can you put the version of `workflows/pair-workflow-sv.cwl` that you're using, plus what branch you're working from?

I might be missing something because that should be coming from https://github.com/mskcc/beagle/blob/develop/runner/operator/roslin_operator/construct_roslin_pair.py#L207, which is a single string.

**Comment by allanbolipata** [comment]
Pretty sure this was fixed. Closing for now, but we can re-open if it pops up again.
