### ISSUE TITLE
Restart is not setting the right output directory

### ISSUE THREAD

**Issue by nikhil** [mskcc/beagle#727]
```
"output_directory": "/juno/res/ci/voyager/None"
```

**Comment by nikhil** [comment]
This is a critical bug, I am going to bump it up on clickup

**Comment by ionox0** [comment]
@nikhil I think the problem is here:

https://github.com/mskcc/beagle/blob/59d32807885f685f369d517d01d327091d557187/runner/tasks.py#L285

Maybe changing that line to this would fix it:
```
def create_run_task(run_id, inputs, output_directory=''):
```

**Comment by ionox0** [comment]
Actually sorry, it's either here:

https://github.com/mskcc/beagle/blob/f8d45817494f7b1a8dc4c7470dd100455252f3ab/runner/models.py#L204

or here:

https://github.com/mskcc/beagle/blob/59d32807885f685f369d517d01d327091d557187/runner/tasks.py#L338

**Comment by ionox0** [comment]
@aef- Correct me if I'm wrong here, but I think by setting the `r.id` to `None` here:

https://github.com/mskcc/beagle/blob/master/runner/views/run_api_view.py#L247

it is passing that through to `submit_job.delay(r.pk, r.output_directory)`, and then using `os.path.join(run.app.output_directory, str(run_id))` (with "None" as the run_id). 


I think your original intention was to update the run ID instead of setting it to None, so maybe if we use `.refresh_from_db()` after saving the run to the DB we would get the run's new ID:

```
        for r in runs_to_restart:
            samples = r.samples.all()
            ports = r.port_set.filter(port_type=PortType.INPUT)
            r.pk = None
            r.operator_run_id = o.pk
            r.clear().save()
            r.samples.add(*samples)

            r.save()
            r.refresh_from_db()         # <-- ADD THIS LINE
...
...
...
            submit_job.delay(r.pk, r.output_directory)
```

**Comment by ionox0** [comment]
Ah actually I think I know what's happening. In the `Run` model's `save()` method, there is this:

```
        if not self.output_directory:
            pipeline = self.app
            pipeline_output_directory = pipeline.output_directory
            self.output_directory = os.path.join(pipeline_output_directory, str(self.id))
```

Thus when we call `r.save()`, before the Run gets a new pk, `None` is used to update the `output_directory` of the run.
