### ISSUE TITLE
fastq path issue for manually edited samples. 

### ISSUE THREAD

**Issue by anoronh4** [mskcc/beagle#911]
i noticed that some of the samples where we recently "incremented" the sample id curiously have some of their fastq paths in `/igo/delivery` instead of `/juno/archive/msk/cmo`:
```
$ grep igo/delivery /juno/work/tempo/voyager/sample_mapping.txt | cut -f 1 | sort | uniq 
s_C_A0FD9E_P004_d2
s_C_JKNJFT_M001_d2
s_C_JKNJFT_N001_d2
```
for some, the archived copy of the file does not exist under `/juno/archive/msk/cmo`, but i assume it must have at one point because these were imported normally before we decided to manually increment the id.

**Comment by allanbolipata** [comment]
@anoronh4 these are because some of the files for these samples had `IDT_Exome_v2_Viral_Probes` or `IDT_Exome_v1_FP_Viral_Probes` as their recipes, which weren't in the set of WES recipes queued for batch migration.

It also wasn't in regular automated CMO storage move logic until July 27 (these samples look to have been imported into Voyager on 06/15/2021). 

New samples/requests for these recipes will automatically import and transfer to CMO storage space so that shouldn't be an issue, but we should talk about what to do with these lingering ones. 

I'm a little unclear as to exactly what's going on with some of these samples - s_C_JKNJFT_N001_d2 and s_C_JKNJFT_M001_d2 both have an entry for paths `/igo/delivery` and `/juno/archive/msk/cmo` registered in the DB, but it looks like duplicated files. They are represented as having both `WholeExomeSequencing` and `IDT_Exome_v2_FP_Viral_Probes`.

My current theory is that they were queued for import at two different times: once with `IDT_Exome_v2_FP_Viral_Probes`, the other when these same requests were updated on the LIMS to `WholeExomeSequencing`. The older metadata was set for import first, then the updated metadata was queued for import after.

They just happened to have been processed through the queue at around the same time, and now exists as two separate entries per fastq file when in reality they should be just one fastq each.

**My proposed solution is I can remove these `/igo/delivery` entries for samples s_C_JKNJFT_N001_d2 and s_C_JKNJFT_M001_d2 , taking care to make sure they actually ARE duplicated, and then that should resolve them.**

Sample s_C_A0FD9E_P004_d2, on the other hand, has no such issues other than not having been transferred to CMO storage space prior to registration to beagle db. **The fix for this is to either delete the entry and re-import or manually do the transfer. I can do the first option if you are comfortable with that as that is easier.**

**Comment by allanbolipata** [comment]
These should be resolved; please review the mapping files and let me know if there are still any issues.

**Comment by allanbolipata** [comment]
I checked the mapping file - there are no more `/igo/delivery` paths so I'm closing this issue.
